export CUDA_VISIBLE_DEVICES=0,1,2,3

e_layers=5
d_layers=5
train_epochs=5
l_w=100000
s_w=1

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_TransformerV2  --model Transformer   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_AutoformerV2   --model Autoformer   --data WADI_F   --features M  --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_InformerV2   --model Informer   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_iTransformerV2 --model iTransformer   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_FEDFormerV2   --model FEDformer   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_TimesNetV2  --model TimesNet   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_ReformerV2   --model Reformer   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec

python -u run.py   --task_name enc_dec_anomaly   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --data_path WADI_train.csv   --model_id WADI_enc_dec_DLinearV2   --model DLinear   --data WADI_F   --features M   --seq_len 5   --label_len 5   --pred_len 5 --n_heads 8 --d_model 256 --enc_in 123 --e_layers $e_layers --dec_in 123  --d_layers $d_layers --c_out 123 --d_ff 1024 --factor 1   --des 'Exp'   --itr 1 --batch_size 128 --train_epochs $train_epochs --freq s  --win_mode 'hopping' --benchmark_id enc_dec