
python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_1  --model Transformer   --data WADI   --features S   --seq_len 15   --pred_len 15 --label_len 15   --d_model 32   --d_ff 32   --e_layers 1   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 8 --benchmark_id uae_grid_search

python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_2  --model Transformer   --data WADI   --features S   --seq_len 15   --pred_len 15 --label_len 15   --d_model 32   --d_ff 32   --e_layers 3   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 8 --benchmark_id uae_grid_search

python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_3  --model Transformer   --data WADI   --features S   --seq_len 15   --pred_len 15 --label_len 15   --d_model 32   --d_ff 32   --e_layers 3   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 16 --benchmark_id uae_grid_search

python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_4  --model Transformer   --data WADI   --features S   --seq_len 15   --pred_len 15 --label_len 15   --d_model 16   --d_ff 16   --e_layers 3   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 8 --benchmark_id uae_grid_search

python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_5  --model Transformer   --data WADI   --features S   --seq_len 15   --pred_len 15 --label_len 15   --d_model 64   --d_ff 64   --e_layers 3   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 8 --benchmark_id uae_grid_search

python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_6  --model Transformer   --data WADI   --features S   --seq_len 30   --pred_len 30 --label_len 30   --d_model 64   --d_ff 64   --e_layers 3   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 8 --benchmark_id uae_grid_search

python -u run.py   --task_name anomaly_detection_uae   --is_training 1   --root_path ./dataset/anomaly_detection/WADI/WADI2019_power_transformed  --model_id Transformer_UAE_grid_search_v2_7  --model Transformer   --data WADI   --features S   --seq_len 15   --pred_len 15 --label_len 15   --d_model 64   --d_ff 64   --e_layers 3   --enc_in 123  --c_out 1   --batch_size 128   --train_epochs 1  --num_workers 0 --n_heads 8 --benchmark_id uae_grid_search
 